// <auto-generated />
using System;
using AfriPay.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AfriPay.Migrations.SandboxDb
{
    [DbContext(typeof(SandboxDbContext))]
    [Migration("20260503092849_InitialCreate_phase2")]
    partial class InitialCreate_phase2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AfriPay.Domain.Balance.BalanceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("text");

                    b.Property<long>("RunningBalance")
                        .HasColumnType("bigint");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BalanceEntries");
                });

            modelBuilder.Entity("AfriPay.Domain.Balance.MerchantBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AvailableBalance")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<long>("PendingBalance")
                        .HasColumnType("bigint");

                    b.Property<long>("ReservedBalance")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MerchantBalances");
                });

            modelBuilder.Entity("AfriPay.Domain.Currency.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("EffectiveRate")
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("OfficialRate")
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Spread")
                        .HasColumnType("numeric(6,5)");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt")
                        .IsDescending();

                    b.ToTable("exchange_rates", null, t =>
                        {
                            t.HasComment("Append-only. Never UPDATE. Insert new row for each rate refresh.");
                        });
                });

            modelBuilder.Entity("AfriPay.Domain.Fee.FeeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FixedAmount")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("MaxAmount")
                        .HasColumnType("bigint");

                    b.Property<long?>("MaxFee")
                        .HasColumnType("bigint");

                    b.Property<long>("MinAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RatePercent")
                        .HasColumnType("numeric");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FeeRules");
                });

            modelBuilder.Entity("AfriPay.Domain.Kyb.KybApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BusinessType")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LegalRepresentativeEmail")
                        .HasColumnType("text");

                    b.Property<string>("LegalRepresentativeName")
                        .HasColumnType("text");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaxId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KybApplications");
                });

            modelBuilder.Entity("AfriPay.Domain.Kyb.KybDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("KybApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KybId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KybApplicationId");

                    b.ToTable("KybDocuments");
                });

            modelBuilder.Entity("AfriPay.Domain.Merchants.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("key_type");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("idx_api_keys_hash_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("idx_api_keys_merchant_id");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("AfriPay.Domain.Merchants.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pricing_plan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("merchants", (string)null);
                });

            modelBuilder.Entity("AfriPay.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProviderUsed")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UssdCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ussd_code");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("AfriPay.Domain.Refunds.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EstimatedArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPartial")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("Status")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("MerchantId", "CreatedAt");

                    b.ToTable("refunds", (string)null);
                });

            modelBuilder.Entity("AfriPay.Domain.Webhooks.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("MerchantId");

                    b.HasIndex("NextRetryAt")
                        .HasFilter("status IN ('pending','retrying')");

                    b.ToTable("webhook_deliveries", (string)null);
                });

            modelBuilder.Entity("AfriPay.Domain.Currency.ExchangeRate", b =>
                {
                    b.OwnsOne("AfriPay.Domain.Currency.CurrencyPair", "Pair", b1 =>
                        {
                            b1.Property<Guid>("ExchangeRateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("From")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("from_currency")
                                .IsFixedLength();

                            b1.Property<string>("To")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("to_currency")
                                .IsFixedLength();

                            b1.HasKey("ExchangeRateId");

                            b1.HasIndex("From", "To");

                            b1.ToTable("exchange_rates");

                            b1.WithOwner()
                                .HasForeignKey("ExchangeRateId");
                        });

                    b.Navigation("Pair")
                        .IsRequired();
                });

            modelBuilder.Entity("AfriPay.Domain.Kyb.KybDocument", b =>
                {
                    b.HasOne("AfriPay.Domain.Kyb.KybApplication", null)
                        .WithMany("Documents")
                        .HasForeignKey("KybApplicationId");
                });

            modelBuilder.Entity("AfriPay.Domain.Merchants.ApiKey", b =>
                {
                    b.HasOne("AfriPay.Domain.Merchants.Merchant", null)
                        .WithMany("ApiKeys")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AfriPay.Domain.Merchants.Merchant", b =>
                {
                    b.OwnsOne("AfriPay.Domain.Merchants.ValueObjects.MerchantLimits", "Limits", b1 =>
                        {
                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("CanAccessAllProviders")
                                .HasColumnType("boolean")
                                .HasColumnName("all_providers");

                            b1.Property<int>("MonthlyTransactionLimit")
                                .HasColumnType("integer")
                                .HasColumnName("monthly_tx_limit");

                            b1.Property<int>("RatePerMinute")
                                .HasColumnType("integer")
                                .HasColumnName("rate_per_minute");

                            b1.HasKey("MerchantId");

                            b1.ToTable("merchants");

                            b1.WithOwner()
                                .HasForeignKey("MerchantId");
                        });

                    b.OwnsOne("AfriPay.Domain.Merchants.ValueObjects.WebhookConfig", "WebhookConfig", b1 =>
                        {
                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Secret")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("webhook_secret");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("webhook_url");

                            b1.HasKey("MerchantId");

                            b1.ToTable("merchants");

                            b1.WithOwner()
                                .HasForeignKey("MerchantId");
                        });

                    b.OwnsOne("AfriPay.Domain.Merchants.ValueObjects.KybInfo", "KybInfo", b1 =>
                        {
                            b1.Property<Guid>("merchant_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .IsFixedLength();

                            b1.Property<string>("LegalName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<string>("RegistrationNumber")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateOnly>("SubmittedAt")
                                .HasColumnType("date");

                            b1.HasKey("merchant_id");

                            b1.ToTable("merchant_kyb", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("merchant_id");
                        });

                    b.Navigation("KybInfo");

                    b.Navigation("Limits")
                        .IsRequired();

                    b.Navigation("WebhookConfig");
                });

            modelBuilder.Entity("AfriPay.Domain.Payments.Payment", b =>
                {
                    b.OwnsOne("AfriPay.Domain.Payments.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("currency")
                                .IsFixedLength();

                            b1.HasKey("PaymentId");

                            b1.ToTable("payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.OwnsOne("AfriPay.Domain.Payments.ValueObjects.Money", "Fee", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("fee_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("fee_currency");

                            b1.HasKey("PaymentId");

                            b1.ToTable("payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.OwnsOne("AfriPay.Domain.Payments.ValueObjects.Money", "Net", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("net_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("net_currency");

                            b1.HasKey("PaymentId");

                            b1.ToTable("payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.OwnsMany("AfriPay.Domain.Payments.PaymentStatusTransition", "Transitions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Actor")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FromStatus")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ToStatus")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("PaymentId");

                            b1.ToTable("payment_status_transitions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.OwnsMany("AfriPay.Domain.Payments.ProviderAttempt", "Attempts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("AttemptedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ErrorCode")
                                .HasColumnType("text");

                            b1.Property<string>("ErrorMessage")
                                .HasColumnType("text");

                            b1.Property<int?>("LatencyMs")
                                .HasColumnType("integer");

                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ProviderKey")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ProviderReference")
                                .HasColumnType("text");

                            b1.Property<bool>("Success")
                                .HasColumnType("boolean");

                            b1.HasKey("Id");

                            b1.HasIndex("PaymentId");

                            b1.ToTable("provider_attempts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.OwnsOne("AfriPay.Domain.Payments.ValueObjects.CustomerInfo", "Customer", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("customer_email");

                            b1.Property<string>("Name")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("customer_name");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("customer_phone");

                            b1.HasKey("PaymentId");

                            b1.ToTable("payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Attempts");

                    b.Navigation("Customer");

                    b.Navigation("Fee");

                    b.Navigation("Net");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("AfriPay.Domain.Refunds.Refund", b =>
                {
                    b.OwnsOne("AfriPay.Domain.Payments.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RefundId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("currency")
                                .IsFixedLength();

                            b1.HasKey("RefundId");

                            b1.ToTable("refunds");

                            b1.WithOwner()
                                .HasForeignKey("RefundId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("AfriPay.Domain.Webhooks.WebhookDelivery", b =>
                {
                    b.OwnsMany("AfriPay.Domain.Webhooks.DeliveryAttempt", "Attempts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("AttemptNumber")
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset>("AttemptedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FailureReason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<int?>("HttpStatusCode")
                                .HasColumnType("integer");

                            b1.Property<int?>("LatencyMs")
                                .HasColumnType("integer");

                            b1.Property<string>("ResponseBody")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<bool>("Success")
                                .HasColumnType("boolean");

                            b1.HasKey("Id");

                            b1.HasIndex("DeliveryId");

                            b1.ToTable("webhook_delivery_attempts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");
                        });

                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("AfriPay.Domain.Kyb.KybApplication", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("AfriPay.Domain.Merchants.Merchant", b =>
                {
                    b.Navigation("ApiKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
