global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    environment: production
    app: afripay

# Alerting 
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

# Scrape configs
scrape_configs:

  # API AfriPay — métriques ASP.NET Core
  - job_name: "afripay-api"
    static_configs:
      - targets: ["afripay-api:8080"]
    metrics_path: /metrics
    scheme: http

  # PostgreSQL Live
  - job_name: "postgres-live"
    static_configs:
      - targets: ["postgres-live:5432"]

  # Redis
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  # Prometheus lui-même
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]