---
all:
  children:
    afripay:
      children:
        api:
          hosts:
            afripay-staging-01:
              ansible_host: "{{ lookup('env', 'STAGING_HOST') }}"
              ansible_port: 22
              ansible_user: root

  vars:
    ansible_python_interpreter: /usr/bin/python3
    app_env: staging
    domain_api:     staging-api.afripay.io
    domain_metrics: staging-metrics.afripay.io
    image_tag: develop